language: csharp

os: linux # Ubuntu 14.04
dist: trusty
group: edge
sudo: required

services:
  - docker

script:
  - ./build.sh

deploy:
  provider: script
  script:
    - ./build.sh -t Publish
  on:
    branch: master